# Site settings
title: Jose Tupayachi
# description: Jekyll Theme Minimal Resume
# baseurl: "https://jtupayachi.github.io/"
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://jtupayachi.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jose Tupayachi
# user_description: I'm a Software Engineer from Argentina, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in world of Giving Circles working with Grapevine, a California based startup trying to improve the world through collaborative giving. I'm the first engineer they hired to work on the platform.
user_title: Industrial Engineer
email: jtupayachi@vols.utk.edu
# twitter_username: lorem_ipsum
linkedin_username: jose-tupayachi-582339147
google_scholar: Kyn6Et8AAAAJ
github_username:  jtupayachi

# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

