# Site settings
title: My Jekyll Site with Particles.js
description: A simple Jekyll site enhanced with Particle.js for dynamic background effects.
author: Your Name
url: "https://your-website-url.com" # Change this to your actual site URL
baseurl: ""  # Leave this empty if your site is hosted at the root level

# Optional, for GitHub Pages or custom domains:
# url: "https://jtupayachi.github.io"  # Your GitHub Pages URL
# baseurl: "/my-awesome-site"     # Use if the site is in a subfolder on GitHub Pages

# The default layout to use for pages and posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Pagination settings (optional, if you're using pagination)
paginate: 5
paginate_path: "/page:num/"

# Markdown and syntax highlighting settings (optional)
markdown: kramdown
highlighter: rouge

# Plugins (optional, for adding functionality like SEO, sitemap, etc.)
plugins:
  - jekyll-seo-tag  # SEO plugin for generating meta tags
  - jekyll-sitemap  # Plugin to generate a sitemap.xml file
  - jekyll-feed     # Plugin to add RSS feed support

# URL Settings for Assets
# For local development or when using GitHub Pages
include:
  - "_assets"  # Add assets like custom scripts or images if you're keeping them in this folder

# Custom collections (optional)
collections:
  # Example collection for a custom section like 'portfolio'
  portfolio:
    output: true  # Makes the collection available in your site

# Exclude files or directories from the final build (optional)
exclude:
  - "README.md"
  - "LICENSE"
  - ".git"
  - ".DS_Store"
  - "node_modules"

# Permalinks settings (optional)
permalink: /:categories/:title/
permalink_defaults:
  format: pretty

