# Site settings
title: Mauricio Urraco
description: Jekyll Theme Minimal Resume
baseurl: ""  # Leave as "" if you're using the root of your GitHub Pages site
url: "https://jtupayachi.github.io"  # Make sure to use "https://"

# User settings
username: Mauricio Urraco
user_description: I'm a Software Engineer from Argentina, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in world of Giving Circles working with Grapevine, a California based startup trying to improve the world through collaborative giving. I'm the first engineer they hired to work on the platform.
user_title: Software Engineer
email: mauriurraco@gmail.com
linkedin_username: murraco
github_username: murraco

# Other settings
exclude: ['package.json', 'src', 'node_modules', 'vendor']
